Delete-and-ignore generated data which is blocking the release
 Error:  Failed to execute goal org.apache.maven.plugins:maven-release-plugin:3.0.1:prepare (default-cli) on project quarkus-bon-jova-rockstar-parent: Cannot prepare the release because you have local modifications :
Error:  [lyrics/src/main/resources/max-lyrics-rating.data:modified]
Error:  [lyrics/src/main/resources/word-counts.data:modified]